### PR TITLE
Add SIP-0010

### PR DESCRIPTION
**Pull request by Semisol**

### CODE REVIEW

**Comment by derekross** [comment]
As stated on Twitter, this allows us to gauge an actual cost fiat cost of the bitcoins to be stacked on Stackchain versus just a random amount of time mining and finally deciding to withdrawal the mined bitcoins. While I am not fully behind this new type of Stackchain stack, I can be in agreement that these guidelines are better than what we've seen attempted. Approved for me as is.

**Comment by FREEBORN-MAN** [comment]
Having a rule forcing someone to dox an address is not cool. If that's not the intention I would just re-word that.

**Comment by sat-hoarder** [comment]
I like that it's simple and easy to understand.  Actual fiat cost is the only way.  Perhaps a sanitized address would be acceptable.  Obfuscated amount and txid same as screenshots of buys should be acceptable.

**Comment by PsyduckSpyduck** [comment]
I support this SIP except for minor typos like the 24th line being labeled 5) when it should be 6). It seems to me a fair way to integrate miners onto Stackchain without compromising the burn fiat for sats tradition

**Review by PsyduckSpyduck — APPROVED** [review]
Much cleaner. Easier to understand. I like the built in way to appeal node rejection with more proof.

**Review by FREEBORN-MAN — APPROVED** [review]

**Pull request merged**
